version: '3.8'

services:
  lmpe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lmpe_web_${NAME_ENV}
    ports:
      - "${WEB_PORT}:80"
    restart: always

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./ConfigProxy/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
